// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZgo2IzV5LO3-iTusE-1y52nicQofYnFo',
    appId: '1:526229807541:web:588c7b9a745c061cac79fc',
    messagingSenderId: '526229807541',
    projectId: 'ipfg-39fae',
    authDomain: 'ipfg-39fae.firebaseapp.com',
    storageBucket: 'ipfg-39fae.appspot.com',
    measurementId: 'G-SCXHHKKW2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_GrhByIgI9HpAb-MBbtcCARsLCTDMY38',
    appId: '1:526229807541:android:585a4c2ea2182b07ac79fc',
    messagingSenderId: '526229807541',
    projectId: 'ipfg-39fae',
    storageBucket: 'ipfg-39fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5tIglmb9mdNa3U16V9C4UC9SgvTdG9_4',
    appId: '1:526229807541:ios:626b7e7e23e2c4ceac79fc',
    messagingSenderId: '526229807541',
    projectId: 'ipfg-39fae',
    storageBucket: 'ipfg-39fae.appspot.com',
    iosBundleId: 'com.example.iwayplus.purple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5tIglmb9mdNa3U16V9C4UC9SgvTdG9_4',
    appId: '1:526229807541:ios:3bc78e3908008cf0ac79fc',
    messagingSenderId: '526229807541',
    projectId: 'ipfg-39fae',
    storageBucket: 'ipfg-39fae.appspot.com',
    iosBundleId: 'com.example.iwayplus.untitled.RunnerTests',
  );
}
